"""initial schema with cascade delete

Revision ID: 55788741f299
Revises: 
Create Date: 2025-11-19 15:09:04.735039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55788741f299'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('discriminator', sa.String(), nullable=True),
    sa.Column('global_name', sa.String(), nullable=True),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('bot', sa.Boolean(), nullable=True),
    sa.Column('system', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('edited_timestamp', sa.DateTime(), nullable=True),
    sa.Column('tts', sa.Boolean(), nullable=True),
    sa.Column('mention_everyone', sa.Boolean(), nullable=True),
    sa.Column('mentions', sa.JSON(), nullable=True),
    sa.Column('mention_roles', sa.JSON(), nullable=True),
    sa.Column('mention_channels', sa.JSON(), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('embeds', sa.JSON(), nullable=True),
    sa.Column('reactions', sa.JSON(), nullable=True),
    sa.Column('nonce', sa.String(), nullable=True),
    sa.Column('pinned', sa.Boolean(), nullable=True),
    sa.Column('webhook_id', sa.BigInteger(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('activity', sa.JSON(), nullable=True),
    sa.Column('application', sa.JSON(), nullable=True),
    sa.Column('application_id', sa.BigInteger(), nullable=True),
    sa.Column('flags', sa.Integer(), nullable=True),
    sa.Column('message_reference', sa.JSON(), nullable=True),
    sa.Column('referenced_message_id', sa.BigInteger(), nullable=True),
    sa.Column('interaction_metadata', sa.JSON(), nullable=True),
    sa.Column('components', sa.JSON(), nullable=True),
    sa.Column('sticker_items', sa.JSON(), nullable=True),
    sa.Column('stickers', sa.JSON(), nullable=True),
    sa.Column('role_subscription_data', sa.JSON(), nullable=True),
    sa.Column('resolved', sa.JSON(), nullable=True),
    sa.Column('poll', sa.JSON(), nullable=True),
    sa.Column('call', sa.JSON(), nullable=True),
    sa.Column('thread', sa.JSON(), nullable=True),
    sa.Column('message_snapshots', sa.JSON(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('users')
    # ### end Alembic commands ###
