"""message reference(reply)

Revision ID: 695bcf2b0305
Revises: cc07737c7f38
Create Date: 2025-11-20 15:14:06.498659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '695bcf2b0305'
down_revision: Union[str, Sequence[str], None] = 'cc07737c7f38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('referenced_message', sa.JSON(), nullable=True))
    op.drop_column('messages', 'referenced_message_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('referenced_message_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('messages', 'referenced_message')
    # ### end Alembic commands ###
