"""describe changes

Revision ID: bb21b6c0e03b
Revises: 
Create Date: 2025-11-18 17:06:37.612165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb21b6c0e03b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guilds',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('buffering_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('channels',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('type', sa.Enum('text', 'thread', name='channeltype'), nullable=True),
    sa.Column('buffering_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('messages', sa.Column('is_pinned', sa.Boolean(), nullable=True))
    op.add_column('messages', sa.Column('has_embeds', sa.Boolean(), nullable=True))
    op.add_column('messages', sa.Column('has_attachments', sa.Boolean(), nullable=True))
    op.add_column('messages', sa.Column('reaction_count', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('edited_at', sa.DateTime(), nullable=True))
    op.add_column('messages', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'messages', 'channels', ['channel_id'], ['id'])
    op.create_foreign_key(None, 'messages', 'guilds', ['guild_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'deleted_at')
    op.drop_column('messages', 'edited_at')
    op.drop_column('messages', 'reaction_count')
    op.drop_column('messages', 'has_attachments')
    op.drop_column('messages', 'has_embeds')
    op.drop_column('messages', 'is_pinned')
    op.drop_table('channels')
    op.drop_table('guilds')
    # ### end Alembic commands ###
